# -*- coding: utf-8 -*-
"""PHONEPE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GHrqRqX_YhRQkclu1BTDHbHsZPtCVWku
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import json
import pandas as pd

root_path = "/content/drive/MyDrive/data"

# -----------------------------
# Aggregated Transaction
# -----------------------------
def agg_transaction():
    path = os.path.join(root_path, "aggregated/transaction/country/india/state")
    data = []

    for state in os.listdir(path):
        for year in os.listdir(os.path.join(path, state)):
            for file in os.listdir(os.path.join(path, state, year)):
                if file.endswith(".json"):
                    with open(os.path.join(path, state, year, file)) as f:
                        content = json.load(f)
                        if content.get("data") is None:
                            continue
                        try:
                            for item in content["data"]["transactionData"]:
                                for pay in item["paymentInstruments"]:
                                    data.append([
                                        state, int(year), int(file.strip(".json")),
                                        item["name"], pay["count"], pay["amount"]
                                    ])
                        except:
                            continue

    df = pd.DataFrame(data, columns=["state","year","quarter","type","count","amount"])
    df.to_csv("/content/drive/MyDrive/agg_transaction.csv", index=False)


# -----------------------------
# Aggregated Insurance
# -----------------------------
def agg_insurance():
    path = os.path.join(root_path, "aggregated/insurance/country/india/state")
    data = []

    for state in os.listdir(path):
        for year in os.listdir(os.path.join(path, state)):
            for file in os.listdir(os.path.join(path, state, year)):
                if file.endswith(".json"):
                    with open(os.path.join(path, state, year, file)) as f:
                        content = json.load(f)
                        if content.get("data") is None:
                            continue
                        try:
                            for item in content["data"]["transactionData"]:
                                for pay in item["paymentInstruments"]:
                                    data.append([
                                        state, int(year), int(file.strip(".json")),
                                        item["name"], pay["count"], pay["amount"]
                                    ])
                        except:
                            continue

    df = pd.DataFrame(data, columns=["state","year","quarter","type","count","amount"])
    df.to_csv("/content/drive/MyDrive/agg_insurance.csv", index=False)


# -----------------------------
# Aggregated User
# -----------------------------
def agg_user():
    path = os.path.join(root_path, "aggregated/user/country/india/state")
    data = []

    for state in os.listdir(path):
        for year in os.listdir(os.path.join(path, state)):
            for file in os.listdir(os.path.join(path, state, year)):
                if file.endswith(".json"):
                    with open(os.path.join(path, state, year, file)) as f:
                        content = json.load(f)
                        if content.get("data") is None:
                            continue
                        try:
                            for user in content["data"]["usersByDevice"]:
                                data.append([
                                    state, int(year), int(file.strip(".json")),
                                    user["brand"], user["count"], user["percentage"]
                                ])
                        except:
                            continue

    df = pd.DataFrame(data, columns=["state","year","quarter","brand","count","percentage"])
    df.to_csv("/content/drive/MyDrive/agg_user.csv", index=False)


# Run
agg_transaction()
agg_insurance()
agg_user()

print(df.head(10))

print(df.tail())

import os, json, pandas as pd

path = "/content/drive/MyDrive/data/aggregated/user/country/india/state"
data = []

for state in os.listdir(path):
    for year in os.listdir(f"{path}/{state}"):
        for file in os.listdir(f"{path}/{state}/{year}"):
            with open(f"{path}/{state}/{year}/{file}") as f:
                content = json.load(f)

                if content['data']['usersByDevice']:
                    for item in content['data']['usersByDevice']:
                        data.append([
                            state,
                            int(year),
                            int(file.strip('.json')),
                            item['brand'],
                            item['count'],
                            item['percentage']
                        ])

df = pd.DataFrame(data, columns=["state","year","quarter","brand","count","percentage"])

df.to_csv("/content/aggregated_user.csv", index=False)

df.head()

from google.colab import files
files.download("/content/aggregated_user.csv")

import os
import json
import pandas as pd

# Correct path (your Google Drive)
path = "/content/drive/MyDrive/data/aggregated/insurance/country/india/state"

data = []

for state in os.listdir(path):
    state_path = os.path.join(path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, 'r') as f:
                content = json.load(f)

                # Check if data exists
                if content.get('data') and content['data'].get('transactionData'):

                    for item in content['data']['transactionData']:
                        for payment in item['paymentInstruments']:

                            data.append({
                                "state": state,
                                "year": int(year),
                                "quarter": int(file.strip('.json')),
                                "type": item['name'],
                                "count": payment['count'],
                                "amount": payment['amount']
                            })

# Create DataFrame
df = pd.DataFrame(data)

# Save CSV
df.to_csv("/content/aggregated_insurance.csv", index=False)

# Preview
df.head()

from google.colab import files
files.download("/content/aggregated_insurance.csv")

import os
import json
import pandas as pd

path = "/content/drive/MyDrive/data/map/transaction/hover/country/india/state"

data = []

for state in os.listdir(path):
    for year in os.listdir(f"{path}/{state}"):
        for file in os.listdir(f"{path}/{state}/{year}"):

            with open(f"{path}/{state}/{year}/{file}") as f:
                content = json.load(f)

                if content.get('data') and content['data'].get('hoverDataList'):

                    for item in content['data']['hoverDataList']:
                        data.append({
                            "state": state,
                            "year": int(year),
                            "quarter": int(file.strip('.json')),
                            "district": item['name'],
                            "count": item['metric'][0]['count'],
                            "amount": item['metric'][0]['amount']
                        })

df = pd.DataFrame(data)
df.to_csv("/content/map_transaction.csv", index=False)

df.head()

from google.colab import files
files.download("/content/map_transaction.csv")

import os
import json
import pandas as pd

path = "/content/drive/MyDrive/data/map/user/hover/country/india/state"

data = []

for state in os.listdir(path):
    for year in os.listdir(f"{path}/{state}"):
        for file in os.listdir(f"{path}/{state}/{year}"):

            with open(f"{path}/{state}/{year}/{file}") as f:
                content = json.load(f)

                if content.get('data') and content['data'].get('hoverData'):

                    for district, values in content['data']['hoverData'].items():
                        data.append({
                            "state": state,
                            "year": int(year),
                            "quarter": int(file.strip('.json')),
                            "district": district,
                            "registeredUsers": values['registeredUsers'],
                            "appOpens": values['appOpens']
                        })

df = pd.DataFrame(data)
df.to_csv("/content/map_user.csv", index=False)

df.head()

from google.colab import files
files.download("/content/map_user.csv")



import os
print(os.listdir("/content/drive/MyDrive/data/map"))

import os
import json
import pandas as pd

path = "/content/drive/MyDrive/data/map/insurance/hover/country/india/state"

data = []

for state in os.listdir(path):
    for year in os.listdir(f"{path}/{state}"):
        for file in os.listdir(f"{path}/{state}/{year}"):

            with open(f"{path}/{state}/{year}/{file}") as f:
                content = json.load(f)

                if content.get('data') and content['data'].get('hoverDataList'):

                    for item in content['data']['hoverDataList']:
                        data.append({
                            "state": state,
                            "year": int(year),
                            "quarter": int(file.strip('.json')),
                            "district": item['name'],
                            "count": item['metric'][0]['count'],
                            "amount": item['metric'][0]['amount']
                        })

df = pd.DataFrame(data)
df.to_csv("/content/map_insurance.csv", index=False)

df.head()

from google.colab import files
files.download("/content/map_insurance.csv")

import os
import json
import pandas as pd

path = "/content/drive/MyDrive/data/top/transaction/country/india/state"

data = []

for state in os.listdir(path):
    for year in os.listdir(f"{path}/{state}"):
        for file in os.listdir(f"{path}/{state}/{year}"):

            with open(f"{path}/{state}/{year}/{file}") as f:
                content = json.load(f)

                if content.get('data') and content['data'].get('pincodes'):

                    for item in content['data']['pincodes']:
                        data.append({
                            "state": state,
                            "year": int(year),
                            "quarter": int(file.strip('.json')),
                            "entity": item['entityName'],   # pincode
                            "count": item['metric']['count'],
                            "amount": item['metric']['amount']
                        })

df = pd.DataFrame(data)
df.to_csv("/content/top_transaction.csv", index=False)

df.head()



from google.colab import files
files.download("/content/top_transaction.csv")

import os
import json
import pandas as pd

path = "/content/drive/MyDrive/data/top/user/country/india/state"

data = []

for state in os.listdir(path):
    for year in os.listdir(f"{path}/{state}"):
        for file in os.listdir(f"{path}/{state}/{year}"):

            with open(f"{path}/{state}/{year}/{file}") as f:
                content = json.load(f)

                if content.get('data') and content['data'].get('pincodes'):

                    for item in content['data']['pincodes']:
                        data.append({
                            "state": state,
                            "year": int(year),
                            "quarter": int(file.strip('.json')),
                            "entity": item['name'],   # pincode
                            "registeredUsers": item['registeredUsers']
                        })

df = pd.DataFrame(data)
df.to_csv("/content/top_user.csv", index=False)

df.head()



from google.colab import files
files.download("/content/top_user.csv")

import os
import json
import pandas as pd

path = "/content/drive/MyDrive/data/top/insurance/country/india/state"

data = []

for state in os.listdir(path):
    for year in os.listdir(f"{path}/{state}"):
        for file in os.listdir(f"{path}/{state}/{year}"):

            with open(f"{path}/{state}/{year}/{file}") as f:
                content = json.load(f)

                if content.get('data') and content['data'].get('pincodes'):

                    for item in content['data']['pincodes']:
                        data.append({
                            "state": state,
                            "year": int(year),
                            "quarter": int(file.strip('.json')),
                            "entity": item['entityName'],
                            "count": item['metric']['count'],
                            "amount": item['metric']['amount']
                        })

df = pd.DataFrame(data)
df.to_csv("/content/top_insurance.csv", index=False)

df.head()



from google.colab import files
files.download("/content/top_insurance.csv")

df.to_csv("/content/drive/MyDrive/agg_insurance.csv", index=False)

import os
import json

path = "/content/drive/MyDrive/data/map/transaction/hover/country/india/state"

state = os.listdir(path)[0]
year = os.listdir(os.path.join(path, state))[0]
file = os.listdir(os.path.join(path, state, year))[0]

file_path = os.path.join(path, state, year, file)

with open(file_path, "r") as f:
    data = json.load(f)

print(data)

print(data["data"]["hoverDataList"])

for item in data["data"]["hoverDataList"]:
    print(
        "District:", item["name"],
        "| Count:", item["metric"][0]["count"],
        "| Amount:", item["metric"][0]["amount"]
    )

import pandas as pd

rows = []

for item in data["data"]["hoverDataList"]:
    rows.append({
        "district": item["name"],
        "count": item["metric"][0]["count"],
        "amount": item["metric"][0]["amount"]
    })

df = pd.DataFrame(rows)

print(df.head())

path = "/content/drive/MyDrive/data/map/user/hover/country/india/state"

with open(file_path, "r") as f:
    data = json.load(f)

print(data["data"]["hoverDataList"])

import os
import json

path = "/content/drive/MyDrive/data/top/transaction/country/india/state"

state = os.listdir(path)[0]
year = os.listdir(os.path.join(path, state))[0]
file = os.listdir(os.path.join(path, state, year))[0]

file_path = os.path.join(path, state, year, file)

with open(file_path, "r") as f:
    data = json.load(f)

print(data)

data["data"]["districts"]

for item in data["data"]["districts"]:
    print(
        "District:", item["entityName"],
        "| Count:", item["metric"]["count"],
        "| Amount:", item["metric"]["amount"]
    )

for item in data["data"]["pincodes"]:
    print(
        "Pincode:", item["entityName"],
        "| Count:", item["metric"]["count"],
        "| Amount:", item["metric"]["amount"]
    )

import pandas as pd

rows = []

for item in data["data"]["districts"]:
    rows.append({
        "district": item["entityName"],
        "count": item["metric"]["count"],
        "amount": item["metric"]["amount"]
    })

df = pd.DataFrame(rows)

print(df.head())